import './style.css';
import { createSpaceRenderer } from './scene.js';
const $=id=>document.getElementById(id),c=$('game'),W=960,H=540;
const names=['VOLCANIC FRONTIER','CRYSTAL CAVERNS','ANCIENT SENTINELS','ORBITAL GRAVEYARD','BIO MECHANICAL','FORTRESS APPROACH','THE FINAL CORE'];
const colors=['#ef7348','#6bdcee','#ba9ae8','#829bba','#92da82','#f1b85b','#ff657f'];
const powerNames=['SPEED','MISSILE','DOUBLE','LASER','OPTION','SHIELD'];
$('slots').innerHTML=powerNames.map((n,i)=>`<div class="slot" id="slot${i}"><small>0${i+1}</small>${n}</div>`).join('');
let state='title',keys={},bullets=[],enemies=[],shots=[],caps=[],particles=[],history=[],boss=null,player,score=0,lives=3,stage=0,time=0,world=0,spawn=0,fire=0,missileTimer=0,selected=-1,transition=0,shake=0,codeIndex=0,cheat=false,muted=false,audio,beat=0,extra=20000,toastTimer=0,last=0,high=0;
try{high=Number(localStorage.getItem('gradius-high'))||0}catch{}
const code=['ArrowUp','ArrowUp','ArrowDown','ArrowDown','ArrowLeft','ArrowRight','ArrowLeft','ArrowRight','b','a'];
function resetPlayer(){player={x:130,y:270,speed:0,missile:false,weapon:'normal',options:0,shield:0,inv:3};history=[];selected=-1}
resetPlayer();
function tone(freq,duration=.08,type='square',volume=.035,slide=0){if(muted||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(20,slide),audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
function initAudio(){try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume()}catch{}}
function notify(t){$('toast').textContent=t;toastTimer=3}
function sync(){ $('score').textContent=String(score).padStart(6,'0');$('high').textContent=String(Math.max(score,high)).padStart(6,'0');$('sector').textContent=String(stage+1).padStart(2,'0')+' / 07';$('lives').textContent='× '+String(lives).padStart(2,'0');$('mission').textContent=String(stage+1).padStart(2,'0')+' — '+names[stage];powerNames.forEach((_,i)=>{$('slot'+i).className='slot'+(selected===i?' selected':'')+([player.speed>0,player.missile,player.weapon==='double',player.weapon==='laser',player.options>0,player.shield>0][i]?' equipped':'')});$('state').textContent=state==='play'?(boss?'GUARDIAN ENGAGED':'MISSION ACTIVE'):state==='paused'?'MISSION PAUSED':'SYSTEM READY'}
function record(){if(score>high){high=score;try{localStorage.setItem('gradius-high',high)}catch{}}}
function overlay(title,sub,desc,button){$('overlay').style.display='flex';$('title').textContent=title;$('subtitle').textContent=sub;$('description').textContent=desc;$('start').innerHTML=button+' <span>↗</span>';$('eyebrow').textContent=state==='paused'?'FLIGHT SYSTEMS ON HOLD':state==='win'?'MISSION ACCOMPLISHED':'STAR COMMAND';$('hint').textContent=state==='paused'?'PRESS P OR ENTER TO RESUME':'PRESS ENTER TO START'}
function fullPower(){player.speed=3;player.missile=true;player.weapon='laser';player.options=4;player.shield=3;lives=30;sync()}
function start(){if(!space)return;initAudio();if(state==='paused'){pause();return}score=0;lives=3;stage=0;extra=20000;world=0;time=0;spawn=0;fire=0;transition=0;beat=0;boss=null;bullets=[];enemies=[];shots=[];caps=[];particles=[];resetPlayer();if(cheat)fullPower();state='play';$('overlay').style.display='none';$('bossbar').style.display='none';notify('SECTOR 01 · VOLCANIC FRONTIER');sync()}
function pause(){if(state==='play'){state='paused';keys={};drag=false;overlay('PAUSED','TAKE A BREATHER','Your mission will be right here.','RESUME MISSION')}else if(state==='paused'){state='play';$('overlay').style.display='none'}sync()}
function input(k){if(state==='title'||state==='paused'||state==='over'||state==='win'){if(k===code[codeIndex]){codeIndex++;if(codeIndex===code.length){codeIndex=0;cheat=true;fullPower();initAudio();tone(880,.4,'triangle',.1,1760);notify('KONAMI CODE · FULL POWER · 30 SHIPS')}}else codeIndex=k===code[0]?1:0}}
function upgrade(){if(state!=='play'||selected<0)return;let success=true;if(selected===0){if(player.speed<3)player.speed++;else success=false}if(selected===1){if(!player.missile)player.missile=true;else success=false}if(selected===2){if(player.weapon!=='double')player.weapon='double';else success=false}if(selected===3){if(player.weapon!=='laser')player.weapon='laser';else success=false}if(selected===4){if(player.options<4)player.options++;else success=false}if(selected===5){if(player.shield<3)player.shield=3;else success=false}if(success){notify(powerNames[selected]+' EQUIPPED');selected=-1;tone(440,.2,'triangle',.08,1320);sync()}}
window.addEventListener('keydown',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Enter'].includes(e.key))e.preventDefault();keys[e.code]=true;if(e.repeat)return;input(k);if(k==='Enter'&&state!=='play')start();if(k==='p'||k==='Escape')pause();if(k==='x')upgrade();if(k==='m')toggleSound()});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>{keys={};if(state==='play')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='play')pause()});
$('start').onclick=start;$('pause').onclick=pause;$('upgrade').onclick=upgrade;
function toggleSound(){muted=!muted;$('sound').textContent=muted?'SOUND OFF':'SOUND ON';if(!muted)initAudio()}$('sound').onclick=toggleSound;
$('fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.();else $('screen').requestFullscreen ? $('screen').requestFullscreen().catch(()=>notify('Rotate your device for a wider view')) : notify('Rotate your device for a wider view')};
$('help').onclick=()=>{if(state==='play')pause();$('manual').showModal()};$('close').onclick=()=>$('manual').close();
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();initAudio();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;input(b.dataset.key)});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys[b.dataset.key]=false)});$('touchB').onclick=()=>input('b');$('touchA').onclick=()=>input('a');let drag=false;c.addEventListener('pointerdown',e=>{if(state!=='play')return;drag=true;c.setPointerCapture(e.pointerId);point(e)});c.addEventListener('pointermove',e=>{if(drag)point(e)});for(const ev of ['pointerup','pointercancel','lostpointercapture'])c.addEventListener(ev,()=>drag=false);function point(e){const r=c.getBoundingClientRect();player.x=Math.max(20,Math.min(920,(e.clientX-r.left)/r.width*W));player.y=Math.max(25,Math.min(515,(e.clientY-r.top)/r.height*H))}
function terrain(x,top=false){const s=world+x;const base=stage===0?26:stage===1?60:stage===2?35:stage===3?22:stage===4?54:stage===5?46:34;return base+Math.sin(s*.007+(top?2:0))*16+Math.sin(s*.019+stage)*10+Math.max(0,Math.sin(s*.004+(top?4:0)))*(stage===1?65:40)}
function burst(x,y,color,n=18){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,v=40+Math.random()*180;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.3+Math.random()*.6,color})}}
function addScore(n){score+=n;if(score>=extra){lives++;extra+=20000;notify('EXTRA SHIP');tone(1000,.25,'triangle')}sync()}
function hit(){if(player.inv>0||state!=='play')return;if(player.shield){player.shield--;player.inv=1;burst(player.x,player.y,'#80eaff',8);tone(160,.2,'sawtooth',.04);sync();return}burst(player.x,player.y,'#ff8153',45);shake=12;tone(170,.5,'sawtooth',.08,25);lives--;if(lives<=0){state='over';record();overlay('GAME OVER','THE STARS REMEMBER','Score '+score.toLocaleString()+' · Sector '+(stage+1)+' of 7','TRY AGAIN')}else{resetPlayer();shots=[];notify('SHIP LOST · REBUILD YOUR POWER')}sync()}
function spawnWave(){const kind=Math.floor(time/4)%5;if(kind===0||kind===3){let group={left:5};for(let i=0;i<5;i++)enemies.push({x:1000+i*48,y:130+Math.random()*240,base:110+(Math.sin(time)*.5+.5)*280,phase:i*.6,t:0,type:'wave',hp:1,r:15,group,red:kind===0,cool:2+Math.random()})}else if(kind===1){for(let i=0;i<3;i++)enemies.push({x:1000+i*125,y:100+Math.random()*330,t:0,type:'hunter',hp:2+Math.floor(stage/3),r:19,red:i===1,cool:1+Math.random()})}else if(kind===2){const top=Math.random()>.5;enemies.push({x:1000,y:0,top,t:0,type:'turret',hp:4,r:20,red:true,cool:1})}else{enemies.push({x:1020,y:270,t:0,type:'spinner',hp:7,r:27,red:true,cool:1})}}
function shoot(x,y){const laser=player.weapon==='laser';bullets.push({x:x+17,y,vx:laser?860:650,vy:0,r:laser?5:3,damage:laser?2:1,life:1.6,laser,hit:new Set()});if(player.weapon==='double')bullets.push({x:x+10,y:y-6,vx:510,vy:-290,r:3,damage:1,life:1.5,hit:new Set()})}
function enemyShot(x,y,speed=150,angle=null){const a=angle??Math.atan2(player.y-y,player.x-x);shots.push({x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:5})}
function makeBoss(){boss={x:1090,y:270,t:0,hp:95+stage*30,max:95+stage*30,cool:1,phase:0};enemies=[];caps=[];$('bossbar').style.display='block';$('bossname').textContent=['BIG CORE','CRYSTAL WARDEN','STONE EMPEROR','IRON DREADNOUGHT','BIO CORE','FORTRESS KEEPER','BRAIN OF THE ARMADA'][stage];notify('WARNING · GUARDIAN APPROACHING');sync()}
function update(dt){toastTimer-=dt;if(toastTimer<0)$('toast').textContent='';if(state!=='play')return;time+=dt;world+=dt*(70+stage*7);fire-=dt;missileTimer-=dt;beat+=dt;player.inv=Math.max(0,player.inv-dt);shake=Math.max(0,shake-dt*25);if(beat>.22){beat=0;const melody=[110,165,220,165,130.81,196,261.63,196,146.83,220,293.66,220,164.81,246.94,329.63,246.94];tone(melody[Math.floor(time/.22)%16],.13,'triangle',.017)}let dx=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0),dy=(keys.ArrowDown||keys.KeyS?1:0)-(keys.ArrowUp||keys.KeyW?1:0);const norm=Math.hypot(dx,dy)||1;player.x=Math.max(20,Math.min(920,player.x+dx/norm*(230+player.speed*55)*dt));player.y=Math.max(15,Math.min(525,player.y+dy/norm*(230+player.speed*55)*dt));history.unshift({x:player.x,y:player.y});if(history.length>100)history.pop();if(keys.Space||keys.KeyZ||drag){if(fire<=0){fire=player.weapon==='laser'?.16:.13;shoot(player.x,player.y);for(let i=1;i<=player.options;i++){const p=history[Math.min(history.length-1,i*14)];shoot(p.x-i*18,p.y)}tone(player.weapon==='laser'?680:900,.045,'square',.013,250)}if(player.missile&&missileTimer<=0){missileTimer=.4;bullets.push({x:player.x,y:player.y+10,vx:230,vy:180,r:5,damage:3,life:4,missile:true,hit:new Set()})}}
if(player.y<terrain(player.x,true)+9||player.y>H-terrain(player.x)-9)hit();
if(!boss&&!transition){spawn-=dt;if(spawn<=0){spawn=Math.max(1.7,3.2-stage*.2);spawnWave()}if(time>46)makeBoss()}
for(const e of enemies){e.t+=dt;e.x-=dt*(e.type==='hunter'?150:95+stage*7);if(e.type==='wave')e.y=e.base+Math.sin(e.t*3+e.phase)*70;if(e.type==='hunter')e.y+=Math.sin(e.t*2)*dt*65;if(e.type==='spinner')e.y=270+Math.sin(e.t*2)*150;if(e.type==='turret')e.y=e.top?terrain(e.x,true)+10:H-terrain(e.x)-10;e.cool-=dt;if(e.cool<=0&&e.x<930&&e.x>player.x){e.cool=e.type==='turret'?1.5:2.6;enemyShot(e.x-12,e.y,140+stage*13);if(e.type==='spinner')for(let i=0;i<6;i++)enemyShot(e.x,e.y,110,i*Math.PI/3+e.t)}if(Math.hypot(player.x-e.x,player.y-e.y)<e.r+10)hit()}
if(boss){boss.t+=dt;boss.x=Math.max(760,boss.x-dt*80);boss.y=270+Math.sin(boss.t*(.7+stage*.06))*145;boss.cool-=dt;if(boss.cool<0&&boss.x<940){boss.cool=Math.max(.42,1.1-stage*.075);const a=Math.atan2(player.y-boss.y,player.x-boss.x);for(let i=-1-Math.floor(stage/3);i<=1+Math.floor(stage/3);i++)enemyShot(boss.x-70,boss.y,180+stage*10,a+i*.2);if(stage>=2)for(let i=0;i<8;i++)enemyShot(boss.x,boss.y,110,boss.t+i*Math.PI/4)}if(Math.abs(player.x-boss.x)<90&&Math.abs(player.y-boss.y)<80)hit();$('bosshealth').style.width=100*boss.hp/boss.max+'%'}
for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.missile&&b.y>H-terrain(b.x)-8){b.y=H-terrain(b.x)-8;b.vy=0;b.vx=370}if(!b.missile&&(b.y<terrain(b.x,true)||b.y>H-terrain(b.x)))b.life=0;for(const e of enemies){if(e.hp<=0||b.hit.has(e))continue;if(Math.abs(b.x-e.x)<e.r+(b.laser?35:6)&&Math.abs(b.y-e.y)<e.r){e.hp-=b.damage;b.hit.add(e);burst(b.x,b.y,'#c4f4ff',3);if(!b.laser)b.life=0;if(e.hp<=0){burst(e.x,e.y,e.red?'#ff7956':'#77dafa');addScore(e.type==='turret'?350:150);tone(90,.12,'sawtooth',.024,35);if(e.group)e.group.left--;if((e.red&&!e.group)||(e.group&&e.group.left===0))caps.push({x:e.x,y:e.y,t:0})}if(b.life<=0)break}}if(boss&&Math.abs(b.x-(boss.x-30))<65&&Math.abs(b.y-boss.y)<29&&!b.hit.has(boss)){boss.hp-=b.damage;b.hit.add(boss);b.life=0;burst(b.x,b.y,'#8cecff',4);if(boss.hp<=0){burst(boss.x,boss.y,colors[stage],100);shake=20;addScore(5000+stage*1500);boss=null;shots=[];bullets=[];transition=4;$('bossbar').style.display='none';notify('SECTOR CLEAR · +'+(5000+stage*1500));tone(110,.7,'sawtooth',.08,30);break}}}
for(const s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;if(Math.hypot(s.x-player.x,s.y-player.y)<s.r+8){hit();s.x=-100}}for(const p of caps){p.x-=dt*75;p.t+=dt;if(Math.hypot(p.x-player.x,p.y-player.y)<28){p.x=-100;selected=(selected+1)%6;addScore(100);tone(700,.12,'triangle',.06,1400);sync()}}
for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}enemies=enemies.filter(e=>e.x>-50&&e.hp>0);bullets=bullets.filter(b=>b.x<1100&&b.life>0&&b.y>-20);shots=shots.filter(s=>s.x>-20&&s.x<1020&&s.y>-20&&s.y<560);caps=caps.filter(p=>p.x>-30);particles=particles.filter(p=>p.life>0);
if(transition){transition-=dt;if(transition<=0){transition=0;stage++;if(stage===7){stage=6;state='win';record();overlay('VICTORY','THE GALAXY IS YOURS','Seven sectors liberated · Score '+score.toLocaleString(),'FLY AGAIN')}else{time=0;spawn=1;shots=[];enemies=[];bullets=[];caps=[];player.inv=3;notify('SECTOR '+String(stage+1).padStart(2,'0')+' · '+names[stage])}sync()}}}
let space;
try { space = createSpaceRenderer(c); }
catch(error) {
  $('title').textContent='OFFLINE';
  $('description').textContent='3D rendering is unavailable. Open in Safari or Chrome with WebGL enabled.';
  $('start').disabled=true;
  console.error('WebGL initialization failed',error);
}
function draw(dt){space?.render({state,player,bullets,enemies,shots,caps,particles,history,boss,stage,time,world,shake,terrain,colors},dt)}
c.addEventListener('webglcontextlost', e=>{e.preventDefault();if(state==='play')pause();notify('GRAPHICS INTERRUPTED · RELOAD TO RESUME')});
c.addEventListener('webglcontextrestored', ()=>notify('GRAPHICS RESTORED · PRESS P TO RESUME'));
function loop(t){const dt=Math.min((t-last)/1000||.016,1/30);last=t;update(dt);draw(dt);requestAnimationFrame(loop)}sync();requestAnimationFrame(loop);
// Suppress native selection/callout gestures only on the interactive game surface.
for (const surface of document.querySelectorAll('.console, .touch')) {
  for (const eventName of ['contextmenu', 'selectstart', 'dragstart']) {
    surface.addEventListener(eventName, event => event.preventDefault());
  }
}
